### ISSUE TITLE
Evaluation with E2E scripts

### ISSUE THREAD

**Issue by andreasvlachos** [superthierry/NLG#2]
It is important to evaluate using the e2e scripts from here:

https://github.com/tuetschek/e2e-metrics

They use a different implementation of BLEU score.

**Comment by MingjieChen** [comment]
I can not run his evaluation code because of some weird bug like can not import some package , I am trying to rewrite his convert.py code, to make it run on my machine.

**Comment by andreasvlachos** [comment]
So the NIST&BLEU scores were added. Here are those of the [baseline](http://www.macs.hw.ac.uk/InteractionLab/E2E/). We are a bit worse, but not much!

Metric | Score
-- | --
BLEU | 0.6925
NIST | 8.4781
METEOR | 0.4703
ROUGE-L | 0.7257
CIDEr | 2.3987
